### ISSUE TITLE
How do you verify it's working

### ISSUE THREAD

**Issue by jfolz** [m42e/mayan-automatic-metadata#11]
I added MAM to my compose yaml (with some modifications to make it work, and the [example plugins](https://github.com/m42e/mayan-automatic-metadata-plugins)) and created an automated workflow for new documents that fires a request to `http://mayan-mam-web:8000/{{document.id}}` on `ocr_ready` like so:

![image](https://user-images.githubusercontent.com/3245870/115887199-fe425b80-a451-11eb-9966-68c7cd3c28ac.png)

Now stuff seems to be happening, but I can't tell if anything is being done to my documents.
Is there a way to verify that MAM is working as intended here?

mayan-mam-worker log:
```
rq mode
14:26:31: Registering birth of worker 9e03f2e6568c44c1a9daea34060fc9c1
14:26:31: Worker rq:worker:9e03f2e6568c44c1a9daea34060fc9c1: started, version 1.2.0
14:26:31: *** Listening on mam...
14:26:31: Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
14:26:31: *** Listening on mam...
14:26:31: Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
14:26:58: mam: mam.single('28') (273810f2-5582-472d-868b-85b3798a153a)
14:26:58: Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
14:26:58: Sent heartbeat to prevent worker timeout. Next one should arrive within 35 seconds.
2021-04-23 14:27:00,927 rq.worker DEBUG Handling successful execution of job 273810f2-5582-472d-868b-85b3798a153a
2021-04-23 14:27:00,928 rq.worker INFO mam: Job OK (273810f2-5582-472d-868b-85b3798a153a)
2021-04-23 14:27:00,929 rq.worker INFO Result is kept for 500 seconds
14:27:00: Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
14:27:00: Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
14:27:00: *** Listening on mam...
14:27:00: Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
14:28:00: mam: mam.single('29') (73c1835b-f989-4f73-a5bf-94c5d483be45)
14:28:00: Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
14:28:00: Sent heartbeat to prevent worker timeout. Next one should arrive within 35 seconds.
2021-04-23 14:28:02,543 rq.worker DEBUG Handling successful execution of job 73c1835b-f989-4f73-a5bf-94c5d483be45
2021-04-23 14:28:02,544 rq.worker INFO mam: Job OK (73c1835b-f989-4f73-a5bf-94c5d483be45)
2021-04-23 14:28:02,544 rq.worker INFO Result is kept for 500 seconds
14:28:02: Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
14:28:02: Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
14:28:02: *** Listening on mam...
14:28:02: Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
```

**Comment by jfolz** [comment]
I noticed the `USE_GIT_PLUGINS` variable and set it to 1. Now this happens:

```
2021-04-23 16:11:57,526 mam ERROR Could not load module telekom
Traceback (most recent call last):
File "./mam.py", line 101, in process
mod = importlib.import_module(modulename)
File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 783, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "plugins/telekom.py", line 25, in <module>
class TelekomMobilfunk(mambase.RegexMetaDataCheck):
File "plugins/telekom.py", line 34, in TelekomMobilfunk
"post": utils.parse_and_format_date_german,
AttributeError: module 'utils' has no attribute 'parse_and_format_date_german'
2021-04-23 16:11:57,527 mam ERROR Could not load module dpag
Traceback (most recent call last):
File "./mam.py", line 101, in process
mod = importlib.import_module(modulename)
File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 783, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "plugins/dpag.py", line 4, in <module>
class PortoMetaData(mambase.RegexMetaDataCheck):
File "plugins/dpag.py", line 13, in PortoMetaData
"post": utils.parse_and_format_date_german,
AttributeError: module 'utils' has no attribute 'parse_and_format_date_german'
```

**Comment by DrRSatzteil** [comment]
Your first log looks perfectly fine. The second log fails because the example plugins in the repo try to call utils.parse_and_format_date_german though utils.py does not define this function.

My suggestion would be to set USE_GIT_PLUGINS to 0 and create your own plugins based on one of the examples. I recommend to mount the plugin folder from your host to the container so you can easily edit the plugins.

**Comment by m42e** [comment]
@jfolz I am sorry if the example plugins do not work out of the box. I just copied a `bit` of my scripts and removed stuff containing private information (such as customer identification number, ect.)

if you run docker with `-v /your/local/plugin/path:/app/plugin` the local folder will be used for the plugins. Give it a try.

**Comment by BrendanKOz** [comment]
To further extend the original question, how to tell if it's working, and how to troubleshoot when it doesn't?

I have logs similar to above, in that MAM reports triggering, and returning OK, but no metadata is actually changing on my files. The logs within the worker container just show the same information.

Is there a way to make the plugins more verbose, so I can get some further clarification as to why it's not working? The filter didn't match the document? It did match, but the regex wasn't found in the OCR content? etc?

**Comment by DrRSatzteil** [comment]
You can change the log level in the logging.uni in the config folder. Set the log level to
level=DEBUG and you should see why it did not work.
