### ISSUE TITLE
404 upon document loading

### ISSUE THREAD

**Issue by DrRSatzteil** [m42e/mayan-automatic-metadata#5]
Im Running in docker. Worker fails to read document. For whatever reasons the call http://app:8000 "GET /api/documents/3/ seems to return a 404 though all previous requests went through fine. The api gives me a valid answer for this URL when accessing it through the browser from outside of the container...

```
mayan-mam-worker    | 2020-09-10 20:36:45,360 mam          INFO     logging in
mayan-mam-worker    | 2020-09-10 20:36:45,360 mam          INFO     performing initial configuration
mayan-mam-worker    | 2020-09-10 20:36:45,361 mayan        DEBUG    endpoint api call http://app:8000/api/auth/token/obtain/?format=json
mayan-mam-worker    | 2020-09-10 20:36:45,363 urllib3.connectionpool DEBUG    Starting new HTTP connection (1): app:8000
mayan-mam-worker    | 2020-09-10 20:36:45,678 urllib3.connectionpool DEBUG    http://app:8000 "POST /api/auth/token/obtain/?format=json HTTP/1.1" 200 52
mayan-mam-worker    | 2020-09-10 20:36:45,680 mayan        DEBUG    Login returned status: 200
mayan-mam-worker    | 2020-09-10 20:36:45,680 mayan        DEBUG    Response: b'{"token":"39aa449ae4a97c78cec36bb4ddb1fbdca1cebff8"}'
mayan-mam-worker    | 2020-09-10 20:36:45,681 mam          INFO     load meta informations
mayan-mam-worker    | 2020-09-10 20:36:45,681 mayan        DEBUG    endpoint api call http://app:8000/api/content_types/?
mayan-mam-worker    | 2020-09-10 20:36:45,683 urllib3.connectionpool DEBUG    Resetting dropped connection: app
mayan-mam-worker    | 2020-09-10 20:36:45,819 urllib3.connectionpool DEBUG    http://app:8000 "GET /api/content_types/ HTTP/1.1" 200 598
mayan-mam-worker    | 2020-09-10 20:36:45,820 mayan        DEBUG    endpoint api call http://app:8000/api/content_types/?page=2
mayan-mam-worker    | 2020-09-10 20:36:45,822 urllib3.connectionpool DEBUG    Resetting dropped connection: app
mayan-mam-worker    | 2020-09-10 20:36:45,973 urllib3.connectionpool DEBUG    http://app:8000 "GET /api/content_types/?page=2 HTTP/1.1" 200 726
mayan-mam-worker    | 2020-09-10 20:36:45,975 mayan        DEBUG    endpoint api call http://app:8000/api/content_types/?page=3
mayan-mam-worker    | 2020-09-10 20:36:45,976 urllib3.connectionpool DEBUG    Resetting dropped connection: app
mayan-mam-worker    | 2020-09-10 20:36:46,112 urllib3.connectionpool DEBUG    http://app:8000 "GET /api/content_types/?page=3 HTTP/1.1" 200 760
mayan-mam-worker    | 2020-09-10 20:36:46,114 mayan        DEBUG    endpoint api call http://app:8000/api/content_types/?page=4
mayan-mam-worker    | 2020-09-10 20:36:46,115 urllib3.connectionpool DEBUG    Resetting dropped connection: app
mayan-mam-worker    | 2020-09-10 20:36:46,249 urllib3.connectionpool DEBUG    http://app:8000 "GET /api/content_types/?page=4 HTTP/1.1" 200 847
mayan-mam-worker    | 2020-09-10 20:36:46,250 mayan        DEBUG    endpoint api call http://app:8000/api/content_types/?page=5
mayan-mam-worker    | 2020-09-10 20:36:46,252 urllib3.connectionpool DEBUG    Resetting dropped connection: app
mayan-mam-worker    | 2020-09-10 20:36:46,388 urllib3.connectionpool DEBUG    http://app:8000 "GET /api/content_types/?page=5 HTTP/1.1" 200 827
mayan-mam-worker    | 2020-09-10 20:36:46,389 mayan        DEBUG    endpoint api call http://app:8000/api/content_types/?page=6
mayan-mam-worker    | 2020-09-10 20:36:46,391 urllib3.connectionpool DEBUG    Resetting dropped connection: app
mayan-mam-worker    | 2020-09-10 20:36:46,523 urllib3.connectionpool DEBUG    http://app:8000 "GET /api/content_types/?page=6 HTTP/1.1" 200 764
mayan-mam-worker    | 2020-09-10 20:36:46,524 mayan        DEBUG    endpoint api call http://app:8000/api/content_types/?page=7
mayan-mam-worker    | 2020-09-10 20:36:46,526 urllib3.connectionpool DEBUG    Resetting dropped connection: app
mayan-mam-worker    | 2020-09-10 20:36:46,769 urllib3.connectionpool DEBUG    http://app:8000 "GET /api/content_types/?page=7 HTTP/1.1" 200 726
mayan-mam-worker    | 2020-09-10 20:36:46,770 mayan        DEBUG    endpoint api call http://app:8000/api/content_types/?page=8
mayan-mam-worker    | 2020-09-10 20:36:46,772 urllib3.connectionpool DEBUG    Resetting dropped connection: app
mayan-mam-worker    | 2020-09-10 20:36:46,909 urllib3.connectionpool DEBUG    http://app:8000 "GET /api/content_types/?page=8 HTTP/1.1" 200 729
mayan-mam-worker    | 2020-09-10 20:36:46,911 mayan        DEBUG    endpoint api call http://app:8000/api/content_types/?page=9
mayan-mam-worker    | 2020-09-10 20:36:46,912 urllib3.connectionpool DEBUG    Resetting dropped connection: app
mayan-mam-worker    | 2020-09-10 20:36:47,048 urllib3.connectionpool DEBUG    http://app:8000 "GET /api/content_types/?page=9 HTTP/1.1" 200 723
mayan-mam-worker    | 2020-09-10 20:36:47,050 mayan        DEBUG    endpoint api call http://app:8000/api/content_types/?page=10
mayan-mam-worker    | 2020-09-10 20:36:47,051 urllib3.connectionpool DEBUG    Resetting dropped connection: app
mayan-mam-worker    | 2020-09-10 20:36:47,191 urllib3.connectionpool DEBUG    http://app:8000 "GET /api/content_types/?page=10 HTTP/1.1" 200 681
mayan-mam-worker    | 2020-09-10 20:36:47,192 mayan        DEBUG    endpoint api call http://app:8000/api/content_types/?page=11
mayan-mam-worker    | 2020-09-10 20:36:47,194 urllib3.connectionpool DEBUG    Resetting dropped connection: app
mayan-mam-worker    | 2020-09-10 20:36:47,334 urllib3.connectionpool DEBUG    http://app:8000 "GET /api/content_types/?page=11 HTTP/1.1" 200 690
mayan-mam-worker    | 2020-09-10 20:36:47,335 mayan        DEBUG    endpoint api call http://app:8000/api/content_types/?page=12
mayan-mam-worker    | 2020-09-10 20:36:47,337 urllib3.connectionpool DEBUG    Resetting dropped connection: app
mayan-mam-worker    | 2020-09-10 20:36:47,470 urllib3.connectionpool DEBUG    http://app:8000 "GET /api/content_types/?page=12 HTTP/1.1" 200 146
mayan-mam-worker    | 2020-09-10 20:36:47,472 mayan        DEBUG    endpoint api call http://app:8000/api/document_types/?
mayan-mam-worker    | 2020-09-10 20:36:47,474 urllib3.connectionpool DEBUG    Resetting dropped connection: app
mayan-mam-worker    | 2020-09-10 20:36:47,680 urllib3.connectionpool DEBUG    http://app:8000 "GET /api/document_types/ HTTP/1.1" 200 52
mayan-mam-worker    | 2020-09-10 20:36:47,681 mayan        DEBUG    endpoint api call http://app:8000/api/metadata_types/?
mayan-mam-worker    | 2020-09-10 20:36:47,683 urllib3.connectionpool DEBUG    Resetting dropped connection: app
mayan-mam-worker    | 2020-09-10 20:36:47,838 urllib3.connectionpool DEBUG    http://app:8000 "GET /api/metadata_types/ HTTP/1.1" 200 52
mayan-mam-worker    | 2020-09-10 20:36:47,839 mayan        DEBUG    endpoint api call http://app:8000/api/tags/?
mayan-mam-worker    | 2020-09-10 20:36:47,841 urllib3.connectionpool DEBUG    Resetting dropped connection: app
mayan-mam-worker    | 2020-09-10 20:36:48,000 urllib3.connectionpool DEBUG    http://app:8000 "GET /api/tags/ HTTP/1.1" 200 52
mayan-mam-worker    | 2020-09-10 20:36:48,001 mam          INFO     load document 3
mayan-mam-worker    | 2020-09-10 20:36:48,002 mayan        DEBUG    endpoint api call http://app:8000/api/documents/3/?
mayan-mam-worker    | 2020-09-10 20:36:48,003 urllib3.connectionpool DEBUG    Resetting dropped connection: app
mayan-mam-worker    | 2020-09-10 20:36:48,167 urllib3.connectionpool DEBUG    http://app:8000 "GET /api/documents/3/ HTTP/1.1" 404 23
mayan-mam-worker    | 2020-09-10 20:36:48,168 mayan        WARNING  {
mayan-mam-worker    |   "detail": "Not found."
mayan-mam-worker    | }
mayan-mam-worker    | 2020-09-10 20:36:48,171 rq.worker    DEBUG    Handling failed execution of job 73c48fe7-5730-4066-8342-80f276f566ed
mayan-mam-worker    | 2020-09-10 20:36:48,173 rq.worker    ERROR    KeyError: 'latest_version'
mayan-mam-worker    | Traceback (most recent call last):
mayan-mam-worker    |   File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 875, in perform_job
mayan-mam-worker    |     rv = job.perform()
mayan-mam-worker    |   File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 648, in perform
mayan-mam-worker    |     self._result = self._execute()
mayan-mam-worker    |   File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 654, in _execute
mayan-mam-worker    |     return self.func(*self.args, **self.kwargs)
mayan-mam-worker    |   File "./mam.py", line 61, in single
mayan-mam-worker    |     process(m, document)
mayan-mam-worker    |   File "./mam.py", line 76, in process
mayan-mam-worker    |     versions = m.get(document["latest_version"]["url"])
mayan-mam-worker    | KeyError: 'latest_version'
mayan-mam-worker    | Traceback (most recent call last):
mayan-mam-worker    |   File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 875, in perform_job
mayan-mam-worker    |     rv = job.perform()
mayan-mam-worker    |   File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 648, in perform
mayan-mam-worker    |     self._result = self._execute()
mayan-mam-worker    |   File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 654, in _execute
mayan-mam-worker    |     return self.func(*self.args, **self.kwargs)
mayan-mam-worker    |   File "./mam.py", line 61, in single
mayan-mam-worker    |     process(m, document)
mayan-mam-worker    |   File "./mam.py", line 76, in process
mayan-mam-worker    |     versions = m.get(document["latest_version"]["url"])
mayan-mam-worker    | KeyError: 'latest_version'
```

**Comment by DrRSatzteil** [comment]
I can reproduce this when calling the API without being logged in.

**Comment by DrRSatzteil** [comment]
My user had insufficient rights. Don't know yet which rights are required but this issue is closed anyway.
