### ISSUE TITLE
Login seems to be broken with v3.5.1

### ISSUE THREAD

**Issue by kevinpawsey** [m42e/mayan-automatic-metadata#9]
Hi, since updating to EDMS 3.5.1 I get the following crash in the worker log:

```
2020-10-24 16:50:06,538 mam          INFO     logging in,
2020-10-24 16:50:06,539 mam          INFO     performing initial configuration,
2020-10-24 16:50:06,568 rq.worker    ERROR    Exception: Login Failed,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 875, in perform_job,
    rv = job.perform(),
  File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 648, in perform,
    self._result = self._execute(),
  File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 654, in _execute,
    return self.func(*self.args, **self.kwargs),
  File "./mam.py", line 59, in single,
    m = get_mayan(),
  File "./mam.py", line 35, in get_mayan,
    m.login(args["username"], args["password"]),
  File "./mayan.py", line 69, in login,
    raise Exception("Login Failed"),
Exception: Login Failed,
```
I am assuming that there has been a login mechanism that has changed recently in the 3.5 branch.

**Comment by DrRSatzteil** [comment]
I cannot reproduce this. Login is still working for me with Mayan EDMS 3.5.1

**Comment by kevinpawsey** [comment]
I will retry delopying the stack again to see if the image has an issue and will update

**Comment by kevinpawsey** [comment]
Hi there,
you are right, it isn't an issue, it is just something strange with accessing EDMS within a swarm stack ... I can curl the API url from edms_app on http://127.0.0.1:8000/api/, I can also curl the API url to https://edms.[external URL].com... but oddly enough, if I try and access it via http://edms_app:8000/api/ I get a "Bad Request" error.  

Appreciate you having a look, and apologies for the confusion... I shall now have a look at my deployment and see what else could have changed.

I will close this now, as this is not an issue.
